# /* ----  https://github.com/JaKooLit  ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(201E24)
$foreground = rgb(F7F8FD)
$color0 = rgb(46454B)
$color1 = rgb(18142B)
$color2 = rgb(1E1A32)
$color3 = rgb(494562)
$color4 = rgb(6D6A8B)
$color5 = rgb(7A7799)
$color6 = rgb(AEB0BC)
$color7 = rgb(EBECF4)
$color8 = rgb(A4A5AB)
$color9 = rgb(201B39)
$color10 = rgb(282342)
$color11 = rgb(615C83)
$color12 = rgb(928EBA)
$color13 = rgb(A29ECC)
$color14 = rgb(E8EAFA)
$color15 = rgb(EBECF4)
