# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F2327)
$foreground = rgb(EFD5C6)
$color0 = rgb(45494E)
$color1 = rgb(051B2C)
$color2 = rgb(19637B)
$color3 = rgb(19637B)
$color4 = rgb(615C53)
$color5 = rgb(1A647C)
$color6 = rgb(9D6445)
$color7 = rgb(E0BAA5)
$color8 = rgb(9C8274)
$color9 = rgb(07243B)
$color10 = rgb(2284A4)
$color11 = rgb(2284A4)
$color12 = rgb(817A6E)
$color13 = rgb(2386A6)
$color14 = rgb(D1865C)
$color15 = rgb(E0BAA5)
