# Purple palette option
background #141322
foreground #d6ccf8

selection_background #8a6ee6
selection_foreground #141322

cursor #c9b3ff
cursor_text_color #0f1020

# black
color0  #3a3348
color8  #4f4663
# red
color1  #f18bbf
color9  #f18bbf
# green
color2  #9ad7b8
color10 #9ad7b8
# yellow
color3  #e7d39c
color11 #e7d39c
# blue
color4  #8aa0ff
color12 #8aa0ff
# magenta
color5  #b78cff
color13 #b78cff
# cyan
color6  #8fd8e5
color14 #8fd8e5
# white
color7  #d6ccf8
color15 #bfb2ef

active_border_color      #b78cff
inactive_border_color    #3a3348
active_tab_foreground    #141322
active_tab_background    #b78cff
active_tab_font_style    bold-italic
inactive_tab_foreground  #d6ccf8
inactive_tab_background  #2b2640
inactive_tab_font_style  bold
tab_bar_background       none
