# Dotfiles palette (yuu)
background #1c1e2a
foreground #bac2de

selection_background #f6a0ca
selection_foreground #1c1e2a

cursor #f6a0ca
cursor_text_color #000000

# black
color0  #45475a
color8  #585b70
# red
color1  #f38ba8
color9  #f38ba8
# green
color2  #a6e3a1
color10 #a6e3a1
# yellow
color3  #f9e2af
color11 #f9e2af
# blue
color4  #89b4fa
color12 #89b4fa
# magenta
color5  #f6a0ca
color13 #f6a0ca
# cyan
color6  #94e2d5
color14 #94e2d5
# white
color7  #bac2de
color15 #a6adc8

active_border_color      #f6a0ca
inactive_border_color    #45475a
active_tab_foreground    #1c1e2a
active_tab_background    #f6a0ca
active_tab_font_style    bold-italic
inactive_tab_foreground  #f6a0ca
inactive_tab_background  #1c1e2a
inactive_tab_font_style  bold
tab_bar_background       none
