foreground              #FFFFFF
background              #043A56
selection_foreground    #043A56
selection_background    #FFFFFF
cursor                  #CA8560 
cursor_text_color       #101112

active_tab_foreground     #043A56
active_tab_background     #627473
inactive_tab_foreground   #627473
inactive_tab_background   #043A56

# black
color0      #294452
color8      #577C8F

# red
color1      #FFDECC
color9      #F0C2AA

# green
color2      #CCEDFF
color10     #AAD7F0

# yellow
color3      #CCFFFC
color11     #AAF0EC

# blue
color4      #9ACCE6
color12     #9ACCE6

# magenta
color5      #9ACBE6
color13     #9ACBE6

# cyan
color6      #9AE6E1
color14     #9AE6E1

# white
color7      #FFDECC
color15     #F0C2AA
