$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf
#  ___________      _________                        __   
#  \__    ___/      \_   ___ \_______ ___.__._______/  |_ 
#   |    |  ______ /    \  \/\_  __ <   |  |\____ \   __\
#   |    | /_____/ \     \____|  | \/\___  ||  |_> >  |  
#   |____|          \______  /|__|   / ____||   __/|__|  
#                          \/        \/     |__|      

# hyde-meta: gtk-theme=Nordic-Blue
# hyde-meta: icon-theme=Nordzy
env = GTK_THEME,Nordic-Blue

layerrule = blur on, match:namespace ^(waybar)$
