
[urgency_low]
    background = "#65A3A080"
    foreground = "#CCFFFCE6"
    frame_color = "#65A3A003"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A5A6B80"
    foreground = "#CCEDFFE6"
    frame_color = "#3A5A6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
