# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EFD5C6
background         #1F2327
cursor             #88ACB5

active_tab_foreground     #1F2327
active_tab_background     #EFD5C6
inactive_tab_foreground   #EFD5C6
inactive_tab_background   #1F2327

active_border_color   #EFD5C6
inactive_border_color #1F2327
bell_border_color     #051B2C

color0      #45494E
color1		#051B2C
color2		#19637B
color3		#19637B
color4		#615C53
color5		#1A647C
color6		#9D6445
color7		#E0BAA5
color8		#9C8274
color9		#07243B
color10		#2284A4
color11		#2284A4
color12		#817A6E
color13		#2386A6
color14		#D1865C
color15		#E0BAA5
