# /* ----  https://github.com/JaKooLit  ---- */  #
# /* wallust template - colors-kitty */

foreground         #F7F8FD
background         #201E24
cursor             #908DA0

active_tab_foreground     #201E24
active_tab_background     #F7F8FD
inactive_tab_foreground   #F7F8FD
inactive_tab_background   #201E24

active_border_color   #F7F8FD
inactive_border_color #201E24
bell_border_color     #18142B

color0      #46454B
color1		#18142B
color2		#1E1A32
color3		#494562
color4		#6D6A8B
color5		#7A7799
color6		#AEB0BC
color7		#EBECF4
color8		#A4A5AB
color9		#201B39
color10		#282342
color11		#615C83
color12		#928EBA
color13		#A29ECC
color14		#E8EAFA
color15		#EBECF4
