local base = require("persona_theme")

local M = {}

local palettes = {
  ["tokyonight"] = {
    bg = "#1A1B26",
    bg_alt = "#24283B",
    fg = "#C0CAF5",
    secondary = "#414868",
    accent = "#7AA2F7",
    accent_alt = "#BB9AF7",
    error = "#F7768E",
    warning = "#E0AF68",
    info = "#7DCFFF",
    hint = "#A9B1D6",
    success = "#9ECE6A",
    comment = "#565F89",
    keyword = "#BB9AF7",
    func = "#7AA2F7",
    string = "#9ECE6A",
    number = "#FF9E64",
    type = "#7DCFFF",
    property = "#C0CAF5",
    operator = "#89DDFF",
    special = "#E0AF68",
  },
  ["kanagawa"] = {
    bg = "#1F1F28",
    bg_alt = "#2A2A37",
    fg = "#DCD7BA",
    secondary = "#47485D",
    accent = "#7E9CD8",
    accent_alt = "#957FB8",
    error = "#E46876",
    warning = "#C0A36E",
    info = "#7FB4CA",
    hint = "#938AA9",
    success = "#98BB6C",
    comment = "#727169",
    keyword = "#957FB8",
    func = "#7E9CD8",
    string = "#98BB6C",
    number = "#DCA561",
    type = "#7AA89F",
    property = "#DCD7BA",
    operator = "#C0A36E",
    special = "#E6C384",
  },
  ["rose-pine"] = {
    bg = "#191724",
    bg_alt = "#1F1D2E",
    fg = "#E0DEF4",
    secondary = "#393552",
    accent = "#C4A7E7",
    accent_alt = "#9CCFD8",
    error = "#EB6F92",
    warning = "#F6C177",
    info = "#9CCFD8",
    hint = "#C4A7E7",
    success = "#31748F",
    comment = "#6E6A86",
    keyword = "#C4A7E7",
    func = "#9CCFD8",
    string = "#F6C177",
    number = "#EA9A97",
    type = "#9CCFD8",
    property = "#E0DEF4",
    operator = "#C4A7E7",
    special = "#EBBCBA",
  },
  ["catppuccin"] = {
    bg = "#1E1E2E",
    bg_alt = "#313244",
    fg = "#CDD6F4",
    secondary = "#585B70",
    accent = "#CBA6F7",
    accent_alt = "#89B4FA",
    error = "#F38BA8",
    warning = "#F9E2AF",
    info = "#89DCEB",
    hint = "#94E2D5",
    success = "#A6E3A1",
    comment = "#7F849C",
    keyword = "#CBA6F7",
    func = "#89B4FA",
    string = "#A6E3A1",
    number = "#FAB387",
    type = "#F5C2E7",
    property = "#CDD6F4",
    operator = "#94E2D5",
    special = "#F5E0DC",
  },
  ["gruvbox"] = {
    bg = "#282828",
    bg_alt = "#3C3836",
    fg = "#EBDBB2",
    secondary = "#665C54",
    accent = "#B8BB26",
    accent_alt = "#458588",
    error = "#FB4934",
    warning = "#FABD2F",
    info = "#83A598",
    hint = "#D3869B",
    success = "#B8BB26",
    comment = "#928374",
    keyword = "#FB4934",
    func = "#83A598",
    string = "#B8BB26",
    number = "#D79921",
    type = "#8EC07C",
    property = "#EBDBB2",
    operator = "#FE8019",
    special = "#D3869B",
  },
  ["midnight-city"] = {
    bg = "#0C0F19",
    bg_alt = "#12141E",
    fg = "#E6F0FF",
    secondary = "#3C4B6E",
    accent = "#64B4FF",
    accent_alt = "#8CC8FF",
    error = "#FF6B88",
    warning = "#FFD166",
    info = "#64B4FF",
    hint = "#A0C8FF",
    success = "#7EE7C7",
    comment = "#7A8AA6",
    keyword = "#8CC8FF",
    func = "#64B4FF",
    string = "#7EE7C7",
    number = "#FFD166",
    type = "#A0C8FF",
    property = "#E6F0FF",
    operator = "#64B4FF",
    special = "#9AD7FF",
  },
  ["mystic-portal"] = {
    bg = "#0F0C1E",
    bg_alt = "#141228",
    fg = "#FFDCF5",
    secondary = "#64468C",
    accent = "#FF64C8",
    accent_alt = "#8C50DC",
    error = "#FF709D",
    warning = "#FFC857",
    info = "#7DA6FF",
    hint = "#C38CFF",
    success = "#8EF0D2",
    comment = "#9B79B4",
    keyword = "#8C50DC",
    func = "#7DA6FF",
    string = "#8EF0D2",
    number = "#FFC857",
    type = "#C38CFF",
    property = "#FFDCF5",
    operator = "#FF64C8",
    special = "#FF95DF",
  },
}

M.palettes = palettes

local function extras(c, mix)
  local accent_alt = c.accent_alt or c.accent
  local code_bg = mix(c.secondary, c.bg, 0.22)
  local inline_bg = mix(c.accent, c.bg, 0.12)
  local function link(group)
    return { link = group }
  end

  return {
    FloatFooter = { fg = c.comment, bg = c.panel },
    WinBar = { fg = c.fg, bg = c.surface_hi, bold = true },
    WinBarNC = { fg = c.subtle, bg = c.surface },
    QuickFixLine = { bg = c.surface_hi, bold = true },
    Whitespace = { fg = c.surface_hi },
    NormalSB = { fg = c.fg, bg = c.bg },
    SignColumnSB = { fg = c.comment, bg = c.bg },
    DiagnosticFloatingError = { fg = c.error, bg = c.panel },
    DiagnosticFloatingWarn = { fg = c.warning, bg = c.panel },
    DiagnosticFloatingInfo = { fg = c.info, bg = c.panel },
    DiagnosticFloatingHint = { fg = c.hint, bg = c.panel },
    DiagnosticUnnecessary = { fg = c.comment, italic = true },
    DiagnosticDeprecated = { fg = c.comment, strikethrough = true },
    LspInlayHint = { fg = c.comment, bg = code_bg },

    ["@function.builtin"] = { fg = c.func },
    ["@function.method"] = { fg = c.func },
    ["@function.method.call"] = { fg = c.func },
    ["@variable.member"] = { fg = c.property },
    ["@variable.parameter"] = { fg = c.fg },
    ["@label"] = { fg = c.special },
    ["@markup.heading"] = { fg = c.accent, bold = true },
    ["@markup.heading.1.markdown"] = { fg = c.accent, bold = true },
    ["@markup.heading.2.markdown"] = { fg = accent_alt, bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.warning, bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.info, bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.success, bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.hint, bold = true },
    ["@markup.link"] = { fg = c.info, underline = true },
    ["@markup.link.label.markdown_inline"] = { fg = c.info, underline = true },
    ["@markup.link.markdown_inline"] = { fg = accent_alt },
    ["@markup.math"] = { fg = c.special },
    ["@markup.raw"] = { fg = c.string },
    ["@markup.quote"] = { fg = c.comment, italic = true },
    ["@markup.list.unchecked"] = { fg = c.warning },
    ["@markup.list.checked"] = { fg = c.success },
    ["@markup.strong"] = { fg = c.fg, bold = true },
    ["@markup.italic"] = { fg = c.fg, italic = true },
    ["@markup.strikethrough"] = { fg = c.comment, strikethrough = true },
    ["@lsp.type.interface"] = { fg = c.type },
    ["@lsp.type.struct"] = { fg = c.type },
    ["@lsp.type.enum"] = { fg = c.type },
    ["@lsp.type.enumMember"] = { fg = c.constant },
    ["@lsp.type.typeParameter"] = { fg = c.type },
    ["@lsp.type.keyword"] = { fg = c.keyword },

    WhichKey = { fg = c.accent, bold = true },
    WhichKeyBorder = { fg = c.border, bg = c.panel },
    WhichKeyDesc = { fg = c.fg },
    WhichKeyGroup = { fg = c.keyword, bold = true },
    WhichKeyIcon = { fg = c.special },
    WhichKeyIconAzure = { fg = c.func },
    WhichKeyIconBlue = { fg = c.info },
    WhichKeyIconCyan = { fg = c.hint },
    WhichKeyIconGreen = { fg = c.success },
    WhichKeyIconGrey = { fg = c.comment },
    WhichKeyIconOrange = { fg = c.warning },
    WhichKeyIconPurple = { fg = accent_alt },
    WhichKeyIconRed = { fg = c.error },
    WhichKeyIconYellow = { fg = c.warning },
    WhichKeyNormal = { fg = c.fg, bg = c.panel },
    WhichKeySeparator = { fg = c.comment },
    WhichKeyTitle = { fg = accent_alt, bg = c.panel, bold = true },
    WhichKeyValue = { fg = c.comment },

    MasonBackdrop = { bg = mix("#000000", c.bg, 0.58) },
    MasonNormal = { fg = c.fg, bg = c.panel },
    MasonCursorLine = { bg = c.cursorline },
    MasonHeader = { fg = c.bg, bg = c.accent, bold = true },
    MasonHeaderSecondary = { fg = c.bg, bg = accent_alt, bold = true },
    MasonHighlight = { fg = c.accent, bold = true },
    MasonHighlightBlock = { fg = c.bg, bg = c.accent },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.accent, bold = true },
    MasonHighlightSecondary = { fg = accent_alt, bold = true },
    MasonHighlightBlockSecondary = { fg = c.bg, bg = accent_alt },
    MasonHighlightBlockBoldSecondary = { fg = c.bg, bg = accent_alt, bold = true },
    MasonLink = { fg = c.info, underline = true },
    MasonMuted = { fg = c.comment },
    MasonMutedBlock = { fg = c.fg, bg = c.surface_hi },
    MasonMutedBlockBold = { fg = c.fg, bg = c.surface_hi, bold = true },
    MasonError = { fg = c.error, bold = true },
    MasonWarning = { fg = c.warning, bold = true },
    MasonHeading = { fg = c.fg, bold = true },

    TroubleNormal = { fg = c.fg, bg = c.panel },
    TroubleNormalNC = { fg = c.fg, bg = c.panel },
    TroubleText = { fg = c.fg },
    TroublePreview = { bg = c.visual },
    TroubleFilename = { fg = c.fg },
    TroubleDirectory = { fg = accent_alt, bold = true },
    TroubleSource = { fg = c.comment },
    TroubleCode = { fg = c.special },
    TroublePos = { fg = c.comment },
    TroubleCount = { fg = c.accent, bg = c.surface_hi, bold = true },
    TroubleIndent = { fg = c.comment },

    NoiceCmdline = link("MsgArea"),
    NoiceCmdlineIcon = link("DiagnosticSignInfo"),
    NoiceCmdlineIconSearch = link("DiagnosticSignWarn"),
    NoiceCmdlinePrompt = link("Title"),
    NoiceCmdlinePopup = { fg = c.fg, bg = c.panel },
    NoiceCmdlinePopupBorder = { fg = c.accent, bg = c.panel },
    NoiceCmdlinePopupTitle = { fg = accent_alt, bg = c.panel, bold = true },
    NoiceCmdlinePopupBorderSearch = { fg = c.warning, bg = c.panel },
    NoiceConfirm = { fg = c.fg, bg = c.panel },
    NoiceConfirmBorder = { fg = c.border, bg = c.panel },
    NoiceMini = link("MsgArea"),
    NoicePopup = link("NormalFloat"),
    NoicePopupBorder = link("FloatBorder"),
    NoicePopupmenu = link("Pmenu"),
    NoicePopupmenuBorder = link("FloatBorder"),
    NoicePopupmenuMatch = { fg = c.accent, bold = true },
    NoicePopupmenuSelected = link("PmenuSel"),
    NoiceScrollbar = link("PmenuSbar"),
    NoiceScrollbarThumb = link("PmenuThumb"),
    NoiceSplit = link("NormalFloat"),
    NoiceSplitBorder = link("FloatBorder"),
    NoiceVirtualText = link("DiagnosticVirtualTextInfo"),
    NoiceFormatProgressDone = link("Search"),
    NoiceFormatProgressTodo = link("CursorLine"),
    NoiceFormatEvent = { fg = c.comment },
    NoiceFormatKind = { fg = c.comment },
    NoiceFormatDate = { fg = c.special },
    NoiceFormatConfirm = link("CursorLine"),
    NoiceFormatConfirmDefault = link("Visual"),
    NoiceFormatTitle = link("Title"),
    NoiceFormatLevelDebug = { fg = c.comment },
    NoiceFormatLevelTrace = { fg = c.comment },
    NoiceFormatLevelOff = { fg = c.comment },
    NoiceFormatLevelInfo = link("DiagnosticVirtualTextInfo"),
    NoiceFormatLevelWarn = link("DiagnosticVirtualTextWarn"),
    NoiceFormatLevelError = link("DiagnosticVirtualTextError"),
    NoiceLspProgressSpinner = { fg = c.accent },
    NoiceLspProgressTitle = { fg = c.comment },
    NoiceLspProgressClient = { fg = accent_alt, bold = true },
    NoiceCompletionItemMenu = { fg = c.comment },
    NoiceCompletionItemWord = { fg = c.fg },
    NoiceCompletionItemKindDefault = { fg = c.special },

    SnacksNormal = link("NormalFloat"),
    SnacksNormalNC = link("NormalFloat"),
    SnacksTitle = link("FloatTitle"),
    SnacksFooter = { fg = c.comment, bg = c.surface },
    SnacksFooterKey = { fg = c.accent, bg = c.surface_hi, bold = true },
    SnacksFooterDesc = { fg = c.fg, bg = c.surface },
    SnacksWinBar = link("WinBar"),
    SnacksWinBarNC = link("WinBarNC"),
    SnacksWinSeparator = link("FloatBorder"),
    SnacksWinKey = { fg = c.accent, bold = true },
    SnacksWinKeySep = { fg = c.comment },
    SnacksWinKeyDesc = { fg = c.fg },
    SnacksDashboardNormal = { fg = c.fg, bg = c.bg },
    SnacksDashboardDesc = { fg = c.fg },
    SnacksDashboardIcon = { fg = accent_alt },
    SnacksDashboardKey = { fg = c.accent, bold = true },
    SnacksInputNormal = link("NormalFloat"),
    SnacksInputBorder = { fg = c.accent, bg = c.panel },
    SnacksInputTitle = link("FloatTitle"),
    SnacksInputIcon = { fg = c.special },
    SnacksNotifierHistory = { fg = c.fg, bg = c.panel },
    SnacksIndent = { fg = c.surface_hi },
    SnacksIndentScope = { fg = c.accent },
    SnacksIndentChunk = { fg = accent_alt },
    SnacksPickerMatch = { fg = c.accent, bold = true },
    SnacksPickerSpinner = { fg = c.accent },
    SnacksPickerRule = { fg = c.surface_hi },
    SnacksPickerFile = { fg = c.fg },
    SnacksPickerDirectory = { fg = accent_alt, bold = true },
    SnacksPickerDir = { fg = accent_alt },
    SnacksPickerTree = { fg = c.comment },
    SnacksPickerDelim = { fg = c.comment },
    SnacksPickerComment = { fg = c.comment },
    SnacksPickerLabel = { fg = c.special },
    SnacksPickerLink = { fg = c.info, underline = true },
    SnacksPickerLinkBroken = { fg = c.error, strikethrough = true },
    SnacksPickerRow = { fg = c.comment },
    SnacksPickerCol = { fg = c.comment },
    SnacksPickerIdx = { fg = c.comment },
    SnacksPickerTime = { fg = c.comment },
    SnacksPickerBufNr = { fg = c.comment },
    SnacksPickerCode = { fg = c.string },
    SnacksPickerBold = { fg = c.fg, bold = true },
    SnacksPickerItalic = { fg = c.fg, italic = true },
    SnacksPickerDimmed = { fg = c.comment },
    SnacksPickerSpecial = { fg = c.special },
    SnacksPickerCmd = { fg = c.accent },
    SnacksPickerCmdBuiltin = { fg = accent_alt, bold = true },
    SnacksPickerDesc = { fg = c.fg },
    SnacksPickerDiagnosticSource = { fg = c.comment },
    SnacksPickerDiagnosticCode = { fg = c.special },
    SnacksPickerGitCommit = { fg = c.special },
    SnacksPickerGitBranch = { fg = accent_alt },
    SnacksPickerGitBranchCurrent = { fg = c.accent, bold = true },
    SnacksPickerGitDetached = { fg = c.warning },
    SnacksPickerGitDate = { fg = c.comment },
    SnacksPickerGitAuthor = { fg = c.type },
    SnacksPickerGitBreaking = { fg = c.error, bold = true },
    SnacksPickerGitIssue = { fg = c.info, underline = true },
    SnacksPickerGitStatusAdded = { fg = c.success },
    SnacksPickerGitStatusModified = { fg = c.warning },
    SnacksPickerGitStatusDeleted = { fg = c.error },
    SnacksPickerGitStatusRenamed = { fg = c.info },
    SnacksPickerGitStatusCopied = { fg = c.hint },
    SnacksPickerGitStatusUntracked = { fg = c.special },
    SnacksPickerUndoAdded = { fg = c.success },
    SnacksPickerUndoRemoved = { fg = c.error },
    SnacksPickerUndoSaved = { fg = c.info },
    SnacksPickerUndoCurrent = { fg = c.accent, bold = true },
    SnacksPickerLspAttachedBuf = { fg = c.accent, bold = true },
    SnacksPickerLspAttached = { fg = c.success },
    SnacksPickerLspEnabled = { fg = c.success },
    SnacksPickerLspDisabled = { fg = c.warning },
    SnacksPickerLspUnavailable = { fg = c.error },
    SnacksPickerKeymapMode = { fg = c.accent },
    SnacksPickerKeymapLhs = { fg = accent_alt, bold = true },
    SnacksPickerKeymapNowait = { fg = c.warning },
    SnacksPickerKeymapRhs = { fg = c.fg },
    SnacksPickerAuEvent = { fg = c.accent },
    SnacksPickerAuPattern = { fg = accent_alt },
    SnacksPickerAuGroup = { fg = c.special },
    SnacksPickerManPage = { fg = c.accent },
    SnacksPickerManSection = { fg = c.special },
    SnacksPickerManDesc = { fg = c.fg },
    SnacksDiffHeader = { fg = c.accent, bg = inline_bg, bold = true },
    SnacksDiffLabel = { fg = accent_alt, bold = true },
    SnacksDiffAdd = { bg = mix(c.success, c.bg, 0.16) },
    SnacksDiffDelete = { bg = mix(c.error, c.bg, 0.16) },
    SnacksDiffContext = { fg = c.fg },
    SnacksDiffConflict = { bg = mix(c.warning, c.bg, 0.18), bold = true },
    SnacksStatusColumnMark = { fg = c.special, bold = true },
    SnacksZenIcon = { fg = c.accent },

    RenderMarkdownH1 = { fg = c.accent, bold = true },
    RenderMarkdownH2 = { fg = accent_alt, bold = true },
    RenderMarkdownH3 = { fg = c.warning, bold = true },
    RenderMarkdownH4 = { fg = c.info, bold = true },
    RenderMarkdownH5 = { fg = c.success, bold = true },
    RenderMarkdownH6 = { fg = c.hint, bold = true },
    RenderMarkdownH1Bg = { bg = mix(c.accent, c.bg, 0.14) },
    RenderMarkdownH2Bg = { bg = mix(accent_alt, c.bg, 0.14) },
    RenderMarkdownH3Bg = { bg = mix(c.warning, c.bg, 0.14) },
    RenderMarkdownH4Bg = { bg = mix(c.info, c.bg, 0.14) },
    RenderMarkdownH5Bg = { bg = mix(c.success, c.bg, 0.14) },
    RenderMarkdownH6Bg = { bg = mix(c.hint, c.bg, 0.14) },
    RenderMarkdownCode = { bg = code_bg },
    RenderMarkdownCodeInfo = { fg = c.comment, bg = code_bg },
    RenderMarkdownCodeBorder = { fg = c.border, bg = code_bg },
    RenderMarkdownCodeFallback = { fg = c.fg, bg = code_bg },
    RenderMarkdownCodeInline = { fg = c.string, bg = inline_bg },
    RenderMarkdownQuote = { fg = c.comment, italic = true },
    RenderMarkdownQuote1 = { fg = c.accent },
    RenderMarkdownQuote2 = { fg = accent_alt },
    RenderMarkdownQuote3 = { fg = c.warning },
    RenderMarkdownQuote4 = { fg = c.info },
    RenderMarkdownQuote5 = { fg = c.success },
    RenderMarkdownQuote6 = { fg = c.hint },
    RenderMarkdownInlineHighlight = { fg = c.fg, bg = inline_bg },
    RenderMarkdownBullet = { fg = accent_alt },
    RenderMarkdownDash = { fg = c.comment },
    RenderMarkdownSign = { fg = c.border, bg = c.bg },
    RenderMarkdownMath = { fg = c.special },
    RenderMarkdownIndent = { fg = c.surface_hi },
    RenderMarkdownHtmlComment = { fg = c.comment },
    RenderMarkdownLink = { fg = c.info, underline = true },
    RenderMarkdownLinkTitle = { fg = accent_alt },
    RenderMarkdownWikiLink = { fg = c.info, underline = true },
    RenderMarkdownUnchecked = { fg = c.warning },
    RenderMarkdownChecked = { fg = c.success, bold = true },
    RenderMarkdownTodo = { fg = c.info, bold = true },
    RenderMarkdownTableHead = { fg = c.accent, bold = true },
    RenderMarkdownTableRow = { fg = c.fg },
    RenderMarkdownSuccess = link("DiagnosticOk"),
    RenderMarkdownInfo = link("DiagnosticInfo"),
    RenderMarkdownHint = link("DiagnosticHint"),
    RenderMarkdownWarn = link("DiagnosticWarn"),
    RenderMarkdownError = link("DiagnosticError"),
  }
end

function M.apply(name)
  local palette = palettes[name]
  if not palette then
    error(("Unknown Hyprwave palette: %s"):format(name))
  end

  base.apply({
    name = "hyprwave-" .. name,
    colors = palette,
    highlights = extras,
  })
end

return M
