## name: Persona 4 Golden - Midnight Channel
## description: Inspired by the yellow and gold aesthetic of Persona 4 Golden

foreground              #fff8d6
background              #17140a
selection_foreground    #17140a
selection_background    #ffe52c

cursor                  #ffe52c
cursor_text_color       #17140a

url_color               #7fe6ef

active_border_color     #ffe52c
inactive_border_color   #2a2415
bell_border_color       #c22303

active_tab_foreground   #17140a
active_tab_background   #ffe52c
inactive_tab_foreground #7fe6ef
inactive_tab_background #1f1a0e
tab_bar_background      #17140a

color0  #17140a
color8  #3a3218
color1  #c22303
color9  #ff4a2f
color2  #c4d70c
color10 #e5f94a
color3  #faa622
color11 #ffe52c
color4  #7fe6ef
color12 #a7f4fa
color5  #b56cff
color13 #d4a1ff
color6  #5edee8
color14 #b8fbff
color7  #fff8d6
color15 #ffffff
