## name: Persona 5 Royal - Phantom Red
## description: Inspired by the red and black aesthetic of Persona 5 Royal

foreground              #ffffff
background              #0d0d0d
selection_foreground    #ffffff
selection_background    #d92323

cursor                  #d92323
cursor_text_color       #ffffff

url_color               #ff4040

active_border_color     #d92323
inactive_border_color   #1a1a1a
bell_border_color       #f2e852

active_tab_foreground   #ffffff
active_tab_background   #d92323
inactive_tab_foreground #7b7b7b
inactive_tab_background #141414
tab_bar_background      #0d0d0d

color0  #0d0d0d
color8  #2a2a2a
color1  #d92323
color9  #ff3030
color2  #8cff66
color10 #b6ff9e
color3  #f2e852
color11 #fff176
color4  #7b7b7b
color12 #a8a8a8
color5  #b832ff
color13 #d875ff
color6  #00d9ff
color14 #72efff
color7  #ffffff
color15 #ffffff
