# hyde-meta: gtk-theme=Wallbash-Gtk
env = GTK_THEME,Wallbash-Gtk

general {
    col.active_border = rgba(CA8560ff) rgba(523729ff) 45deg
    col.inactive_border = rgba(043A56ff) rgba(096699ff) 45deg
}

group {
    col.border_active = rgba(CA8560ff) rgba(523729ff) 45deg
    col.border_inactive = rgba(043A56cc) rgba(096699cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(101112ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
