#  ___________      _________                        __   
#  \__    ___/      \_   ___ \_______ ___.__._______/  |_ 
#   |    |  ______ /    \  \/\_  __ <   |  |\____ \   __\
#   |    | /_____/ \     \____|  | \/\___  ||  |_> >  |  
#   |____|          \______  /|__|   / ____||   __/|__|  
#                          \/        \/     |__|      

# hyde-meta: gtk-theme=Frosted-Glass
# hyde-meta: icon-theme=Tela-circle-blue
env = GTK_THEME,Frosted-Glass

layerrule = match:namespace ^(waybar)$, blur on
