#  ___________      _________                        __   
#  \__    ___/      \_   ___ \_______ ___.__._______/  |_ 
#   |    |  ______ /    \  \/\_  __ <   |  |\____ \   __\
#   |    | /_____/ \     \____|  | \/\___  ||  |_> >  |  
#   |____|          \______  /|__|   / ____||   __/|__|  
#                          \/        \/     |__|      

# hyde-meta: gtk-theme=Gruvbox-Retro
# hyde-meta: icon-theme=Gruvbox-Plus-Dark
env = GTK_THEME,Gruvbox-Retro

env = HYPRCURSOR_THEME,Gruvbox-Retro
env = HYPRCURSOR_SIZE,20
env = XCURSOR_THEME,Gruvbox-Retro
env = XCURSOR_SIZE,20
exec = hyprctl setcursor Gruvbox-Retro 20

layerrule = blur on, match:namespace ^(waybar)$
